### ISSUE TITLE
Insecure SSL cert verification default

### ISSUE THREAD

**Issue by etingof** [ktdreyer/errata-tool#1]
Consider a refactoring to make SSL cert verification ON by [default](https://github.com/ktdreyer/errata-tool/blob/master/errata_tool/connector.py#L10). Users may be given a chance to disable it explicitly, silent default to skip certificate validation is dangerous!

Thanks!

**Comment by ktdreyer** [comment]
Thanks Ilya, I agree completely. I've changed this behavior in https://github.com/ktdreyer/errata-tool/pull/2
