### ISSUE TITLE
Refactor idea for Erratum._fetch

### ISSUE THREAD

**Issue by yazug** [ktdreyer/errata-tool#12]
Refactor idea is to split out work to other helper functions that do one piece of the work
This would also allow us to better unit test some of the helper work functions for logic and regression purposes

#Baseline flags. section could be moved to self._baseline_flags(erratum)

def _baseline_flags(self, erratum):
    if self.errata_state in ('QE'):
        if 'rhnqa' in erratum and erratum['rhnqa'] == 0:
            self.current_flags.append('needs_distqa')

    if 'doc_complete' in erratum and erratum['doc_complete'] == 0:
        self.current_flags.append('needs_docs')
    if 'security_approved' in erratum and \
       erratum['security_approved'] == 0:
        self.current_flags.append('needs_security')

**Comment by yazug** [comment]
idea branch is here https://github.com/yazug/errata-tool/tree/erratum_fetch_refactor

**Comment by ktdreyer** [comment]
I reviewed that branch, and the changes you've made there are really great. (I really like the stubs for overriding, too). I would merge a PR with those changes if you submit it!

**Comment by ktdreyer** [comment]
Refactor landed in v1.2.4 (PR https://github.com/ktdreyer/errata-tool/pull/13)
